### ISSUE TITLE
Changing UDF

### ISSUE THREAD

**Issue by rtenklooster** [officecenter/Autotask#14]
Hi,
I'm having some problemens updating an udf for a specific account.
I want to get the account:
`$account = Get-AtwsAccount -Id 1
`
Edit a specific UDF (this part I don't understand):
`$account.UserDefinedFields.MyUdf = "Test"`

And then save the account by using inputObject.

This isn't a bug, I just don't get how i'm suppose to do this.

**Comment by klemmestad** [comment]
The shortest: Update directly by Id:
`Set-AtwsAccount -Id 1 -UserDefinedFields @{name='MyUdf'; value='Test'}`

More than one UDF (note: any UDF must already have been defined by GUI or by script):

`Set-AtwsAccount -Id 1 -UserDefinedFields @{name='MyUdf'; value='Test'}, @{name='MyOtherUdf'; value='OtherTest'}`

To support any name for an UDF Autotask has opted for handling them as name/value pairs. A hashtable with 2 keys, name & value can successfully be cast to type Autotask.UserDefinedField. The long version (and possibly the "correct" version):

`$udf = New-Object -Typename Autotask.UserDefinedField`
`$udf.name = 'MyUdf'`
`$udf.value = 'Test'`
`$account = Get-AtwsAccount -Id 1`
`$account.UserDefinedFields = $udf`
`$account | Set-AtwsAccount`

**Comment by rtenklooster** [comment]
Thanks for the fast reply. I had already tried the last option, but i'm getting an arror:
`$udf = New-Object -Typename Autotask.UserDefinedField
$udf.name = 'SpTeamsite'
$udf.value = 'Test'
$account = Get-AtwsAccount -Id 3443
$account.UserDefinedFields = $udf
$account | Set-AtwsAccount`

The error is: 
`
Set-AtwsData : Picklist value [205] does not exist for KeyAccountIcon. 
At line:101634 char:24
`

**Comment by klemmestad** [comment]
That is weird. The message claims that the account with id 3443 has been configured with a key account icon that has since been deleted. To make the change the function downloads the account object with the Id you specify, changes any fields you have specified using parameters (in this case the UDFs) and uploads the changed object. Since you didn’t change the key account icon in the script it sounds like the account had a non-existing key account icon when it was downloaded. I would check that first.
