### ISSUE TITLE
Running on Azure Runbooks (Cache)

### ISSUE THREAD

**Issue by kai-osthoff** [officecenter/Autotask#17]
Hi.

Just struggling with running that Module on Azure Runbooks. A lot of that messages:

Exception calling "ShouldProcess" with "3" argument(s): "A command that prompts the user failed because the host 
 program or the command type does not support user interaction. The host was attempting to request confirmation with the 
 following message: Update-AtwsDiskCache: About to post 128 SOAP queries to Autotask Web API for detailed field info for 
 128 entities. This will take a while. Do you want to continue?"
 At C:\Modules\User\Autotask\Public\Update-AtwsDiskCache.ps1:66 char:9
 + If ($PSCmdlet.ShouldProcess($VerboseDescrition, $VerboseWarning, ...
 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 + CategoryInfo : NotSpecified: (:) [], MethodInvocationException
 + FullyQualifiedErrorId : HostException
 

AND 

Each time i start the runbook, a complete new cache is fired up.

So a short-script takes a long time because it need each time a new cache. Any Idea how i can change that behavior?

Kai.

**Comment by klemmestad** [comment]
Hi,
I haven an updated module currently in beta that I hope will solve this. You trigger the new behavior from Connect-AtwsWebAPI:
```powershell
Import-Module Autotask
Connect-AtwsWebAPI -Credential $Credential -ApiTrackingIdentifier $ApiKey -NoDiskCache
```
The expected behavior is to load all functions from the script files supplied with the module without having to regenerate any cache before your script is run. This behavoir does not support neither parameter validation nor Intellisense for picklist fields, but any picklist label is still converted to its numeric index value at runtime. Your scripts should run unmodified.

If testing goes well I will update the main module today.

**Comment by felix-mueller-ic** [comment]
It worked. There is no confirmation request that stopped the script this time.

**Comment by rtenklooster** [comment]
Hi hugo,
Thanks again for the effort!
I have updates the module to the latest 6.2 version.
When connecting with the -NoDiskCache it's still caching, is this supposed to happen?
![image](https://user-images.githubusercontent.com/6507714/57773136-94729080-7717-11e9-91b3-02adf3dbf5bc.png)

**Comment by klemmestad** [comment]
Yes, it still needs to cache, but it should cache i RAM only. Looking at your output I think I should improve the Verbose messages to say as much, because you can't tell from that output that nothing is written to disk. Does it work OK for you?

**Comment by rtenklooster** [comment]
Okay, nice! Yes it’s working fine. I haven’t tested extensively but a quick account lookup worked fine.
The runbook completed in about 2 minutes so that’s fine!

Outlook voor iOS<https://aka.ms/o0ukef> downloaden

________________________________
Van: Hugo Klemmestad <notifications@github.com>
Verzonden: donderdag, mei 16, 2019 11:04 AM
Aan: officecenter/Autotask
CC: Richard; Comment
Onderwerp: Re: [officecenter/Autotask] Running on Azure Runbooks (Cache) (#17)


Yes, it still needs to cache, but it should cache i RAM only. Looking at your output I think I should improve the Verbose messages to say as much, because you can't tell from that output that nothing is written to disk. Does it work OK for you?

**Comment by kai-osthoff** [comment]
It seems working now, but ...
System.Management.Automation.CommandNotFoundException: The term 'New-AtwsTicket' is not recognized as the name of a cmdlet, 

... the "New-AtwsTicket"-CMDlet is missing!

Kai

**Comment by kai-osthoff** [comment]
Update:

Import-Module Autotask -ArgumentList $Credentials, $ApiKey
Connect-AtwsWebApi -Credential $Credentials -ApiTrackingIdentifier $ApiKey -NoDiskCache

If running without "Connect-AtwsWebApi" it is missing ... with that two lines above it works flawlessly.

Thx a lot.
