### ISSUE TITLE
The specified module was not loaded because no valid module file was found in any module directory.

### ISSUE THREAD

**Issue by dahifi** [officecenter/Autotask#18]
Just installed the module through the Powershell ISE. 
 ```
Import-Module Autotask 
$securepassword = ConvertTo-SecureString -string "PASSWORD" -AsPlainText -Force 
$Credential = new-object System.Management.Automation.PSCredential ("USERNAME", $securepassword)
$ApiKey = "APIKEY"
Connect-AutotaskWebAPI -Credential $Credential -ApiTrackingIdentifier $ApiKey  -Verbose
```
Lots of verbose output...

```
VERBOSE: Removing the imported "Set-AtwsUserDefinedFieldDefinition" function.
VERBOSE: Removing the imported "Set-AtwsWorkTypeModifier" function.
VERBOSE: Removing the imported "Connect-AutotaskWebAPI" alias.
VERBOSE: Populating RepositorySourceLocation property for module Autotask.
VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\Autotask\1.6.2.1\Autotask.psm1'.
Import-Module : The specified module 'C:\Program Files\WindowsPowerShell\Modules\Autotask\1.6.2.1' was not loaded because no valid module file was 
found in any module directory.
At C:\Program Files\WindowsPowerShell\Modules\Autotask\1.6.2.1\Public\Connect-AtwsWebAPI.ps1:80 char:7
+       Import-Module -Name $ModulePath -Global -Prefix $Prefix -Force
+       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (C:\Program File...utotask\1.6.2.1:String) [Import-Module], FileNotFoundException
    + FullyQualifiedErrorId : Modules_ModuleNotFound,Microsoft.PowerShell.Commands.ImportModuleCommand
```

The files are there, not sure what the problem is. 

Also tried loading the module directly with the parameters, but getting an authentication error. User is setup with the API key, credentials and user is set to API user. Also tried full access.

**Comment by dahifi** [comment]
Thanks! This is so awesome. The fact that you auto-generated these methods from the API is AMAZING. 

Where would I look to find out how you did that? Seems like something I could use in other projects and programming languages.

**Comment by klemmestad** [comment]
Sorry, I didn't see this comment before now since you closed the issue - I have a bit of backlog in my mailbox... 😊
 
All the code is included in the module. Most of what you would want to look at are in the Private subdirectory. The convoluted part is the caching. The functions are generated from templates (*-AtwsDefinition.ps1). I use .EntityInfo() to determine which methods are supported (get, set, new, remove) and I use .FieldInfo() to determine which parameters to include and how to validate them. The core of the module is an inner and outer foreach loop:
```powershell
Foreach ($Entity in $Entities) {
  $Fields = $Atws.GetFieldInfo($Entity.name)
  Foreach ($Field in $Fields) {
    # a lot of stuff 
  }
}
```
The challenge is that looking up fieldinfo is slow. To look up fieldinfo for 134 entities every time you load the module was annoyingly slow. So I started caching it. That became complicated rather quickly. But it feels like it is almost there now :)
