### ISSUE TITLE
Switch to skip ApiTrackingIdentifier for backward compatibility?

### ISSUE THREAD

**Issue by JsonWud** [officecenter/Autotask#30]
Hello, I am attempting to test the 1.6.2.11 version of the module due to some date issues I have experienced with version 0.2.2.5 but I am being prompted for an ApiTrackingIdentifier. We are in the process of testing our existing code with the api tracker in our dev environment, but have not transitioned to it in production. Is there no way to skip the ApiTrackingIdentifier for backward compatibility or does the 1.6.2.11 module not work with the 1.5 version of the API at all?

Thanks,
Jason

**Comment by klemmestad** [comment]
No, I am afraid it does not work with 1.5. Version 0.2.2.5 is the last version to work with 1.5. 

And you are right. I have put quite an effort into finally getting the date handling right in the newest module version. I was not seeing the behavior I was lead to expect by the API documentation. I do believe this is caused by some unseen XML processing in the .NET code New-WebServiceProxy is based on. Date handling has been reliable in my tests since version 1.6.2.8, but I would appreciate any feedback you could give me on how it works now.

For testing you could add another API user and activate an ApiTrackingIdentifier on the new user. If you activate an ApiTrackingIdentifier on your existing user you will have to use it to access API version 1.5 as well. A user with an ApiTrackingIdentifier MUST provide the tracker everytime, no matter which API version you try to access.

For what it is worth: In our tests all our old code worked with the new API version unmodified. The changes are mostly additive, new fields and entities have been added.

**Comment by JsonWud** [comment]
Thanks. I'm now using two different API accounts to continue testing both 0.2.2.5 and 1.6.2.x versions of the module.
