### ISSUE TITLE
How to access API methods directly with 1.6.2.x

### ISSUE THREAD

**Issue by JsonWud** [officecenter/Autotask#35]
Hello,

When using the 0.2.2.5 version of the module, I was able to call methods on the $AtwsConnection.Atws object in case I wanted to manually query or create, etc. Now that I am testing with the 1.6.2.11/12 version of the module, I cannot find that same functionality. Am I overlooking a new variable name or is there a different way to call a method directly against the API connection?

Example (this works with 0.2.2.5):
```
$ticketFieldInfo = $AtwsConnection.Atws.GetFieldInfo('ticket')
```

Thanks in advance,
Jason

**Comment by klemmestad** [comment]
You are right. In 1.6.x.x everything is a single module and the connection object isn't exported. Frankly, I wasn't aware that anybody but me bothered to use the object directly 😉 Because of this change I have moved a previously private function `Get-AtwsFieldInfo` to public and improved it a bit. Now you can do
```powershell
$ticketFieldInfo = Get-AtwsFieldInfo -Entity ticket
```
and avoid messing with ATWSResponse yourself. I have also included a wrapper for .ThresholdAndUsageInfo() `Get-AtwsThresholdAndUsageInfo.ps1`

Do you know if you can specify a variable to export manually when running Import-Module? It would have been very nice to export `$Atws` manually from time to time. Particularly when I try to track down bugs... 😊

**Comment by JsonWud** [comment]
Sorry for the delayed reply. The above was just an example, but a real world issue I have is that my API account cannot query the UserDefinedFieldDefinition entity. When I attempt it using a command like this:

```Get-AtwsUserDefinedFieldDefinition -all|ogv```

I receive the following error, no doubt because my internal Autotask administrators are ignorant about permission settings.

```Get-AtwsData : The logged in resource does not have the adequate permissions to query this entity type.
At C:\<my documents path>\WindowsPowershell\Cache\301126\Dynamic\Get-AtwsUserDefinedFieldDefinition.ps1:429 char:15
+     $Result = Get-AtwsData -Entity $EntityName -Filter $Filter
+               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Get-AtwsData
```

However, I can revert to the 0.2.2.5 module and run the following code to get the information I need about the UDFs associated with the account entity:

```$global:AtwsConnection.Atws.getUDFInfo('Account') | ogv```

Perhaps I can modify the connect function to include a new switch that will optionally return the Atws object for direct access. I don't want to continue using two different versions of the module if I can help it.

Thanks again,
Jason

**Comment by klemmestad** [comment]
I have solved it in the simplest way possible: A separate public function `Get-AtwsConnectionObject` that returns the current connection object from the module runspace. New version out now.
