### ISSUE TITLE
Get-AtwsService - No Unit Count?

### ISSUE THREAD

**Issue by s0nders** [officecenter/Autotask#40]
Hola Everyone,

I'm able to query pretty much everything but the main field I'd need for the project I'm working on... Does anyone know if I'm missing something or does the API not have the ability to return service/bundle unit counts? I see unitPrice and unitCost but no count :/ any help would be appreciated!

**Comment by JsonWud** [comment]
Hi @s0nders 
The entity you need is ContractService instead of Service. As services are added to contracts, a new entity is created unique to that account and contract. The contract service is what units are added or removed from over the course of the contract's lifespan.

See the section on the ContractService entity in the API doc to get started.
https://www.autotask.net/help/Content/LinkedDOCUMENTS/WSAPI/T_WebServicesAPIv1_6.pdf

I created a custom function to layout the contract services for a given client in a nice table for review when questions arise about units. You'll have to cross-reference several entities to get all of this info in one place.

![contractservices_table ps1](https://user-images.githubusercontent.com/39089884/61644599-ffd66280-ac72-11e9-8203-fecaa83c155b.png)

**Comment by s0nders** [comment]
Thank you! I really appreciate the quick response,  I love the project btw!!

Get Outlook for Android<https://aka.ms/ghei36>

**Comment by s0nders** [comment]
> Hi @s0nders
> The entity you need is ContractService instead of Service. As services are added to contracts, a new entity is created unique to that account and contract. The contract service is what units are added or removed from over the course of the contract's lifespan.
> 
> See the section on the ContractService entity in the API doc to get started.
> https://www.autotask.net/help/Content/LinkedDOCUMENTS/WSAPI/T_WebServicesAPIv1_6.pdf
> 
> I created a custom function to layout the contract services for a given client in a nice table for review when questions arise about units. You'll have to cross-reference several entities to get all of this info in one place.
> 
> ![contractservices_table ps1](https://user-images.githubusercontent.com/39089884/61644599-ffd66280-ac72-11e9-8203-fecaa83c155b.png)

BTW are you willing to share the function? I'm looking to take these queries and append the results in a tempDB for some reporting functions and that sounds like it would be a great place to start!

**Comment by klemmestad** [comment]
Hi @JsonWud, thank you for helping out! If you can share your script in any way, please do. The autogenerated functions only provide bare bones access to the API, so this kind of more advanced functionality would be very welcome.

I am closing this issue now.

**Comment by JsonWud** [comment]
Hi @s0nders,

So sorry for the delay. I would not be able to share the script that outputs the table above but would be happy to help you create your own if you haven't done so already. This script is in need of refactoring as it is quite old (in software years). 

Basically you want to create an advanced function that takes an account name, or whatever you want to use as an identifier, as a parameter. Inside the function determine the contract from the accountname/id, then pull the contractservices associated with the contract. Once you have the contractservices for that contract, you can pull the contractserviceunits for the date you want to specify as the second parameter. I pull the services as well so that I can cross reference the service name. The rest is just selecting the fields and outputting to Format-Table (I add another optional switch parameter for this because I want to output full objects by default).

At the command line I would call this advanced function like so:

```New-ContractUnitReport -AccountName 'XYZ Client' -Date '7/1/2019' -TableView```

Let me know if you need more help!

Jason

**Comment by s0nders** [comment]
> Hi @s0nders,
> 
> So sorry for the delay. I would not be able to share the script that outputs the table above but would be happy to help you create your own if you haven't done so already. This script is in need of refactoring as it is quite old (in software years).
> 
> Basically you want to create an advanced function that takes an account name, or whatever you want to use as an identifier, as a parameter. Inside the function determine the contract from the accountname/id, then pull the contractservices associated with the contract. Once you have the contractservices for that contract, you can pull the contractserviceunits for the date you want to specify as the second parameter. I pull the services as well so that I can cross reference the service name. The rest is just selecting the fields and outputting to Format-Table (I add another optional switch parameter for this because I want to output full objects by default).
> 
> At the command line I would call this advanced function like so:
> 
> `New-ContractUnitReport -AccountName 'XYZ Client' -Date '7/1/2019' -TableView`
> 
> Let me know if you need more help!
> 
> Jason

Morning JsonWud! 

Thank you for that response! I'm current at the the point where I can pull the units from the contractserviceunits but I'm having an issue narrowing it down to the current specific month like you stated. Would you be able to share how your accomplishing this? I think once I have that piece I should be good front that point. Thank you again for taking the time to assist, I really appreciate it.

**Comment by JsonWud** [comment]
@s0nders 
Glad you figured it out. Don't be hard on yourself. Dealing with time in Autotask is not always a walk in the park. ;)

**Comment by klemmestad** [comment]
@s0nders 
Autotask has a whole section dedicated to explaining ContractUnits in the documentation, but the key takeaway is that for any given `$Date` you'll want the ContractServiceUnit that begins _before_ (or on) and ends _after_ (or on) the date you are interested in:
```powershell
$Units = Get-AtwsContractServiceUnit -ContractID $Contracts.id -StartDate $Date -LessThanOrEquals StartDate -EndDate $Date -GreaterThanOrEquals EndDate
$BundleUnits = Get-AtwsContractServiceBundleUnit -ContractID $Contracts.id -StartDate $Date -LessThanOrEquals StartDate -EndDate $Date -GreaterThanOrEquals EndDate
```
For some reason that is quite possibly rational (I think) you have to get units for service _bundles_ in a separate query. The only difference between the two is that ContractServiceBundleUnit does not have a VendorId field (after all, you could bundle services from different vendors) AND the external reference field is called ContractServiceBundleId, not ContractServiceId. Important differences, those.

It really would be nice if we had a nice, static function that got both entities for any given contract or client, @JsonWud 😉

**Comment by JsonWud** [comment]
Happy to contribute after I get out from under some looming deadlines. :D

**Comment by klemmestad** [comment]
Oh, I know about those - issues on real bugs tend to pop up around those 😉 Best of luck!
