### ISSUE TITLE
No valid module was found

### ISSUE THREAD

**Issue by seanbnd** [officecenter/Autotask#47]
Script was working yesterday but started getting this error today. Updated the module, still error. Removed the module and installed it, error. 

Import-Module : The specified module 'C:\Program Files\WindowsPowerShell\Modules\Autotask\1.6.2.17' with version '1.6.2.17' was not loaded because no valid module file was found in any module directory.
At C:\Program Files\WindowsPowerShell\Modules\Autotask\1.6.2.17\Public\Connect-AtwsWebAPI.ps1:179 char:9

**Comment by klemmestad** [comment]
Do you depend on any advanced options (like -NoDiskCache) or can you load the module straight with credentials?
`Import-Module Autotask -force -ArgumentList $Credentials, $ApiTrackingId`

The current version of Connect-AtwsWebApi relies on the module information supplied by PowerShell in the $MyInvocation variable. For some reason I do not know (patches or updates?) this has not beem reliable lately. I will replace it with more manual methods in the next version.

**Comment by seanbnd** [comment]
Below is my script:

#$Credentials = Get-Credential

$Username = "***********"

$Password = ConvertTo-SecureString -String "*********" -AsPlainText -Force

$Credential = New-Object -TypeName "System.Management.Automation.PSCredential" -ArgumentList $Username, $Password

$ApiTrackingIdentifier = "***********"



$Protocol = [System.Net.ServicePointManager]::SecurityProtocol
If ($Protocol.ToString() -notlike '*Tls12*') { 
  [System.Net.ServicePointManager]::SecurityProtocol += 'tls12'
}
 

Import-Module Autotask


Connect-AtwsWebAPI -Credential $Credential -ApiTrackingIdentifier $ApiTrackingIdentifier


$Timeout = 30 ## seconds


If ((Get-AtwsTicket -Status "New" | Where {$_.CreateDate -ge (Get-Date).AddHours(-2).ToString('g')}).Count -gt 1){start-job {(New-Object Media.SoundPlayer "C:\Scripts\Annoying+Yell.wav").PlaySync()

}}

$nid = (Get-Process powershell).id

Wait-Process -Id $nid -Timeout 120

Stop-Process -Id $nid

**Comment by seanbnd** [comment]
If I just run the Module straight with Creds it looks to load with errors:

Select-String : Cannot bind argument to parameter 'Path' because it is null.
At C:\Program Files\WindowsPowerShell\Modules\Autotask\1.6.2.17\Autotask.psm1:176 char:74
+ ... Select-String -Pattern $VersionString -Path $DynamicFunction.FullName
+                                                 ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Select-String], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.SelectStringCommand
 
Remove-Item : Cannot bind argument to parameter 'Path' because it is null.
At C:\Program Files\WindowsPowerShell\Modules\Autotask\1.6.2.17\Autotask.psm1:181 char:43
+ ...           $Null = Remove-Item -Path $DynamicFunction.fullname -Force  ...
+                                         ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Remove-Item], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.RemoveItemCommand

**Comment by klemmestad** [comment]
The import script complains about not finding your personal cache, even though that part of the code should never run if you do not want one. Could you try importing with -debug? And since `-debug` will cause Import-Module to include `-verbose` - with a prompt for each line! - you'd better include that, too. 
```powershell
Import-Module Autotask -force -verbose -debug -ArgumentList $Credentials, $ApiTrackingId
```

**Comment by seanbnd** [comment]
I was able to get the error to go away and by adding "-force -ArgumentList $Credentials, $$ApiTrackingIdentifier" to my import-module the script started working again. Thank you for the help.

**Comment by dahifi** [comment]
Had some same error, even though I've loaded the module several times in the last few days. Not sure what the issue was, but following code works now: 
```
    If (Get-InstalledModule "Autotask" -ErrorAction SilentlyContinue) {
        Remove-Module "Autotask" -Force -Confirm:$False -ErrorAction SilentlyContinue | Out-Null
        Update-Module "Autotask" -Force -Confirm:$false
    }
    else {
        Install-Module "Autotask" -Force -Confirm:$false
    }

    $username = $env:AUTOTASK_USERNAME
    $password =  ConvertTo-SecureString -string $env:AUTOTASK_PASSWORD -asPlainText -Force
    $Credential = New-Object -TypeName System.Management.Automation.PSCredential -ArgumentList $username, $password
    $AutoTaskAPIToken = $env:AUTOTASK_API_TOKEN
    Import-Module Autotask -force #-ArgumentList $Credential, $AutoTaskAPIToken, UsePickListLabels, '*'
    Connect-AtwsWebAPI  -Credential $Credential -ApiTrackingIdentifier $AutoTaskAPIToken -UsePicklistLabels
```

**Comment by klemmestad** [comment]
A `-verbose -debug` output would be useful for me to understand what is going on. Btw, have you tried to load the module in powershell_ise? Just to rule out any issues with the VSCode PowerShell debugger. Although the symptoms points to the .NET layer and New-WebServiceProxy. The right way to check that requires support for custom namespaces in the module, but that is currently not possible. It is on my to-do list, but it may be a while before I figure out the right way to do it.

**Comment by fluidityUK** [comment]
Has a solution been found to this?  Its causing me a nightmare today.  Seems to have only occurred within the last month though (we only really use the API on the 1st of the month to help with our metered billing).

When running Connect-AutotaskWebAPI i get the same error as above.

have included the verbose debug output below.

VERBOSE: Connect-AtwsWebAPI: Begin of function
VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\Autotask\1.6.2.17\Autotask.psd1'.
VERBOSE: Populating RepositorySourceLocation property for module Autotask.
VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\Autotask\1.6.2.17\Autotask.psm1'.
DEBUG: Autotask.psm1: Loading Manifest file Autotask.psm1 from C:\Program Files\WindowsPowerShell\Modules\Autotask\1.6.2.17
DEBUG: Autotask.psm1: Found 25 script files in C:\Program Files\WindowsPowerShell\Modules\Autotask\1.6.2.17\Private
DEBUG: Autotask.psm1: Found 13 script files in C:\Program Files\WindowsPowerShell\Modules\Autotask\1.6.2.17\Public
DEBUG: Autotask.psm1: Found 210 script files in C:\Program Files\WindowsPowerShell\Modules\Autotask\1.6.2.17\Static
DEBUG: Autotask.psm1: Found 170 script files in C:\Program Files\WindowsPowerShell\Modules\Autotask\1.6.2.17\Dynamic
VERBOSE: Autotask.psm1: Importing 25 Private and 13 Public functions.
DEBUG: Autotask.psm1: Importing C:\Program Files\WindowsPowerShell\Modules\Autotask\1.6.2.17\Private\Compare-PSObject.ps1
DEBUG: Autotask.psm1: Importing C:\Program Files\WindowsPowerShell\Modules\Autotask\1.6.2.17\Private\Connect-AtwsWebServices.ps1
DEBUG: Autotask.psm1: Importing C:\Program Files\WindowsPowerShell\Modules\Autotask\1.6.2.17\Private\Convert-AtwsFunctionToText.ps1
DEBUG: Autotask.psm1: Importing C:\Program Files\WindowsPowerShell\Modules\Autotask\1.6.2.17\Private\ConvertFrom-XML.ps1
DEBUG: Autotask.psm1: Importing C:\Program Files\WindowsPowerShell\Modules\Autotask\1.6.2.17\Private\ConvertTo-AtwsDate.ps1
DEBUG: Autotask.psm1: Importing C:\Program Files\WindowsPowerShell\Modules\Autotask\1.6.2.17\Private\ConvertTo-AtwsFilter.ps1
DEBUG: Autotask.psm1: Importing C:\Program Files\WindowsPowerShell\Modules\Autotask\1.6.2.17\Private\ConvertTo-QueryXML.ps1
DEBUG: Autotask.psm1: Importing C:\Program Files\WindowsPowerShell\Modules\Autotask\1.6.2.17\Private\Copy-PSObject.ps1
DEBUG: Autotask.psm1: Importing C:\Program Files\WindowsPowerShell\Modules\Autotask\1.6.2.17\Private\Export-AtwsDiskCache.ps1
DEBUG: Autotask.psm1: Importing C:\Program Files\WindowsPowerShell\Modules\Autotask\1.6.2.17\Private\Get-AtwsData.ps1
DEBUG: Autotask.psm1: Importing C:\Program Files\WindowsPowerShell\Modules\Autotask\1.6.2.17\Private\Get-AtwsDefinition.ps1
DEBUG: Autotask.psm1: Importing C:\Program Files\WindowsPowerShell\Modules\Autotask\1.6.2.17\Private\Get-AtwsFunctionDefinition.ps1
DEBUG: Autotask.psm1: Importing C:\Program Files\WindowsPowerShell\Modules\Autotask\1.6.2.17\Private\Get-AtwsHelpText.ps1
DEBUG: Autotask.psm1: Importing C:\Program Files\WindowsPowerShell\Modules\Autotask\1.6.2.17\Private\Get-AtwsParameterDefinition.ps1
DEBUG: Autotask.psm1: Importing C:\Program Files\WindowsPowerShell\Modules\Autotask\1.6.2.17\Private\Get-AtwsPSParameter.ps1
DEBUG: Autotask.psm1: Importing C:\Program Files\WindowsPowerShell\Modules\Autotask\1.6.2.17\Private\Get-Copyright.ps1
DEBUG: Autotask.psm1: Importing C:\Program Files\WindowsPowerShell\Modules\Autotask\1.6.2.17\Private\Import-AtwsCmdLet.ps1
DEBUG: Autotask.psm1: Importing C:\Program Files\WindowsPowerShell\Modules\Autotask\1.6.2.17\Private\Import-AtwsDiskCache.ps1
DEBUG: Autotask.psm1: Importing C:\Program Files\WindowsPowerShell\Modules\Autotask\1.6.2.17\Private\New-AtwsData.ps1
DEBUG: Autotask.psm1: Importing C:\Program Files\WindowsPowerShell\Modules\Autotask\1.6.2.17\Private\New-AtwsDefinition.ps1
DEBUG: Autotask.psm1: Importing C:\Program Files\WindowsPowerShell\Modules\Autotask\1.6.2.17\Private\Remove-AtwsData.ps1
DEBUG: Autotask.psm1: Importing C:\Program Files\WindowsPowerShell\Modules\Autotask\1.6.2.17\Private\Remove-AtwsDefinition.ps1
DEBUG: Autotask.psm1: Importing C:\Program Files\WindowsPowerShell\Modules\Autotask\1.6.2.17\Private\Set-AtwsData.ps1
DEBUG: Autotask.psm1: Importing C:\Program Files\WindowsPowerShell\Modules\Autotask\1.6.2.17\Private\Set-AtwsDefinition.ps1
DEBUG: Autotask.psm1: Importing C:\Program Files\WindowsPowerShell\Modules\Autotask\1.6.2.17\Private\Update-AtwsFilter.ps1
DEBUG: Autotask.psm1: Importing C:\Program Files\WindowsPowerShell\Modules\Autotask\1.6.2.17\Public\Connect-AtwsWebAPI.ps1
DEBUG: Autotask.psm1: Importing C:\Program Files\WindowsPowerShell\Modules\Autotask\1.6.2.17\Public\Get-AtwsAttachment.ps1
DEBUG: Autotask.psm1: Importing C:\Program Files\WindowsPowerShell\Modules\Autotask\1.6.2.17\Public\Get-AtwsConnectionObject.ps1
DEBUG: Autotask.psm1: Importing C:\Program Files\WindowsPowerShell\Modules\Autotask\1.6.2.17\Public\Get-AtwsFieldInfo.ps1
DEBUG: Autotask.psm1: Importing C:\Program Files\WindowsPowerShell\Modules\Autotask\1.6.2.17\Public\Get-AtwsInvoiceInfo.ps1
DEBUG: Autotask.psm1: Importing C:\Program Files\WindowsPowerShell\Modules\Autotask\1.6.2.17\Public\Get-AtwsThresholdAndUsageInfo.ps1
DEBUG: Autotask.psm1: Importing C:\Program Files\WindowsPowerShell\Modules\Autotask\1.6.2.17\Public\Get-AtwsWsdlVersion.ps1
DEBUG: Autotask.psm1: Importing C:\Program Files\WindowsPowerShell\Modules\Autotask\1.6.2.17\Public\New-AtwsAttachment.ps1
DEBUG: Autotask.psm1: Importing C:\Program Files\WindowsPowerShell\Modules\Autotask\1.6.2.17\Public\Remove-AtwsAttachment.ps1
DEBUG: Autotask.psm1: Importing C:\Program Files\WindowsPowerShell\Modules\Autotask\1.6.2.17\Public\Uninstall-AtwsOldModuleVersion.ps1
DEBUG: Autotask.psm1: Importing C:\Program Files\WindowsPowerShell\Modules\Autotask\1.6.2.17\Public\Update-AtwsDiskCache.ps1
DEBUG: Autotask.psm1: Importing C:\Program Files\WindowsPowerShell\Modules\Autotask\1.6.2.17\Public\Update-AtwsFunctions.ps1
DEBUG: Autotask.psm1: Importing C:\Program Files\WindowsPowerShell\Modules\Autotask\1.6.2.17\Public\Update-AtwsManifest.ps1
VERBOSE: Autotask.psm1: Credentials detected. Connecting to Autotask API
DEBUG: Autotask.psm1: API tracking identifier for interface@virtualmsp.uk detected.
DEBUG: Autotask.psm1: Credentials for interface@virtualmsp.uk detected.
VERBOSE: Connect-AtwsWebServices: Begin of function
VERBOSE: Connect-AtwsWebServices: Getting ZoneInfo for user \interface@virtualmsp.uk by calling default URI https://webservices.Autotask.net/atservices/1.6/atws.wsdl
VERBOSE: Connect-AtwsWebServices: Customer tenant ID: 808616, Web URL: https://ww16.autotask.net/, SOAP endpoint: https://webservices16.autotask.net/ATServices/1.6/atws.asmx
VERBOSE: Connect-AtwsWebServices: Creating New-WebServiceProxy against URI: https://webservices16.autotask.net/ATServices/1.6/atws.wsdl
VERBOSE: Connect-AtwsWebServices: Running query Get-AtwsData -Entity Resource -Filter "username -eq $UserName"
DEBUG: Get-AtwsData: Begin of function
DEBUG: Update-AtwsFilter: Begin of function
DEBUG: Update-AtwsFilter: Checking query for variables that have survived as string
DEBUG: Get-AtwsData: Converting query string into QueryXml. String as array looks like: Resource, username, -eq, interface
DEBUG: Get-AtwsData: QueryXml looks like: <queryxml><entity>Resource</entity><query><field>username<expression op="Equals">interface</expression></field></query></queryxml>
VERBOSE: Get-AtwsData: Adding looping construct to query to handle more than 500 results.
VERBOSE: Get-AtwsData: Passing QueryXML to Autotask API
DEBUG: Get-AtwsFieldInfo: Begin of function
VERBOSE: Import-AtwsDiskCache: Trying to determine correct location for dynamic module cache.
VERBOSE: Import-AtwsDiskCache: Module cache location is C:\Program Files\WindowsPowerShell\Modules\Autotask\1.6.2.17\Private\AutotaskFieldInfoCache.xml
VERBOSE: Import-AtwsDiskCache: Personal cache location is C:\Users\Administrator\Documents\WindowsPowershell\Cache\AutotaskFieldInfoCache.xml.
VERBOSE: Import-AtwsDiskCache: Reading cache from disk.
VERBOSE: Import-AtwsDiskCache: End of function
VERBOSE: Get-AtwsFieldInfo: Looking up detailed Fieldinfo for entity Resource
DEBUG: Get-AtwsFieldInfo: Returning fieldinfo for entity Resource from cache
DEBUG: Get-AtwsFieldInfo: End of function
DEBUG: Get-AtwsData: End of function
VERBOSE: Connect-AtwsWebServices: Loading disk cache
VERBOSE: Import-AtwsDiskCache: Trying to determine correct location for dynamic module cache.
VERBOSE: Import-AtwsDiskCache: Module cache location is C:\Program Files\WindowsPowerShell\Modules\Autotask\1.6.2.17\Private\AutotaskFieldInfoCache.xml
VERBOSE: Import-AtwsDiskCache: Personal cache location is C:\Users\Administrator\Documents\WindowsPowershell\Cache\AutotaskFieldInfoCache.xml.
VERBOSE: Import-AtwsDiskCache: Reading cache from disk.
VERBOSE: Import-AtwsDiskCache: End of function
VERBOSE: Connect-AtwsWebServices: End of function
DEBUG: Autotask.psm1: Personal disk cache: Found 0 script files in C:\Users\Administrator\Documents\WindowsPowershell\Cache\808616\Dynamic
Import-Module : The specified module 'C:\Program Files\WindowsPowerShell\Modules\Autotask\1.6.2.17' with version '1.6.2.17' was not loaded because no valid module file was found 
in any module directory.
At C:\Program Files\WindowsPowerShell\Modules\Autotask\1.6.2.17\Public\Connect-AtwsWebAPI.ps1:169 char:9
+         Import-Module -Name $ModulePath @ImportParams -Debug -Verbose
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (C:\Program File...totask\1.6.2.17:String) [Import-Module], FileNotFoundException
    + FullyQualifiedErrorId : Modules_ModuleWithVersionNotFound,Microsoft.PowerShell.Commands.ImportModuleCommand
 
VERBOSE: Connect-AtwsWebAPI: End of function
