### ISSUE TITLE
New Ticket Titles with (Copy 1)

### ISSUE THREAD

**Issue by TimBrown-CCS** [officecenter/Autotask#54]
So, we are trying to create tickets by creating Autotask.Ticket objects, and then using New-AtwsTicket -InputObject. However, when we do this it is add "(Copy 1)" to the end of the titles.

`$MasterTicket = New-Object Autotask.Ticket`
`$MasterTicket.AccountId = $client`
`$MasterTicket.DueDateTime = $($(get-date).Date).AddHours(10)`
`$MasterTicket.Priority = 2`
`$MasterTicket.Status = 1`
`$MasterTicket.IssueType = 28`
`$MasterTicket.SubIssueType = 318`
`$MasterTicket.QueueID = $QueueID`
`$MasterTicket.Title = "Title"`
`$MasterTicket.Description = "Description"`
`$MasterTicket.ServiceLevelAgreementID = 1`
`$MasterTicket.TicketType = 3`
`$MasterTicket.TicketCategory = 3`
`$MasterTicket.Source = 8`
`$MasterTicket.EstimatedHours = 0`
`$NewMasterTicket = New-AtwsTicket -InputObject $MasterTicket`

We've now changed the code to use the parameters of the function - creating an identical ticket - and it works without issue. It seems to me that there is an issue either in the Autotask.Ticket object, or in the -InputObject parameter of the function.

Any ideas?

**Comment by klemmestad** [comment]
It is an issue with -InputObject and possibly faulty logic at my part. I have assumed (yes, I know...) that a Ticket object that you pass to New- in most cases are an existing ticket that you wish to copy. And because of Ticket Duplicate Detection(tm) in Autotask a new ticket needs a different title from the old one, or Autotask will simply merge the two tickets. At least this is the behavior I see in our Autotask tenant.

Now that you have made me think it through once more I think I know where I went wrong. I think I know how to fix it and still allow for copying tickets without duplicate ticket detection. Thank you for bringing this to my attention 😊

**Comment by TimBrown-CCS** [comment]
Ah, that makes sense. Thanks for the response :)

**Comment by PhoenixC46** [comment]
Hi, will this be resolved in the new version? I'm using 1.6.9 and still have the "Copy 1" appearing on the end of every ticket created.
Or is there a workaround we can use in the meantime? Thanks

**Comment by klemmestad** [comment]
Sorry, the issue was closed before the fix was implemented and I forgot...
Added fix now (it really was that easy), updated the version and pester is testing the updated version right now. New module version should be out in minutes.
