### ISSUE TITLE
Powershell 7 Preview 4 on OS X

### ISSUE THREAD

**Issue by tmidthjell** [officecenter/Autotask#58]
Module not working with Ps7 and OS X. Seems to be a problem with $MyInvocation.MyCommand.Module - Seems to be empty

**Comment by klemmestad** [comment]
The module does not support PowerShell Core. The Autotask Web Services API is a SOAP API and I use the New-WebServiceProxy cmdlet to interact with it. New-WebServiceProxy is using System.Web.Services.dll which is Windows only. And it seems the .NET Core team is not going to port this to .Core any time soon. 

There is a deeper discussion of this issue here: [SOAP support in all platforms
#9838](https://github.com/PowerShell/PowerShell/issues/9838)

**Comment by tmidthjell** [comment]
Thanks for your answer. Then lets hope that the cmdlet will be available in Powershell 7 soon as Powershell 7 is not the same as "Powershell Core", but rather a rewrite to unify and provide one single version of Powershell across platforms :)

**Comment by klemmestad** [comment]
I have published a module version AutotaksBeta on PowershellGallery with multiplatform support today. It should load and run on a mac (and Linux). Install with `install-module autotaskbeta` and you can use it just like the release module: `import-module autotaskbeta; connect-atwswebapi ...`

So far I have tested it on powershell core 6 only. it works in my tests, but needs a lot more testing before I can release it as a general release. I have not tried it on Powershell 7 yet.
