### ISSUE TITLE
Set-AtwsAccount -TerritoryID <Integer> Fails

### ISSUE THREAD

**Issue by Brainstem2000** [officecenter/Autotask#8]
Set-AtwsAccount : Cannot validate argument on parameter 'TerritoryID'. The argument "<Integer>" does not belong to the set "<char values separated by commas>" specified by the ValidateSet attribute. Supply an argument that is in the set and then try the command again.
At line:1 char:106
    + CategoryInfo          : InvalidData: (:) [Set-AtwsAccount], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Set-AtwsAccount

TerritoryID is an integer value in the dataset. The command is not allowing passing of that integer and complains it is not part of the valid data set. Needs more work.

**Comment by klemmestad** [comment]
I see you closed the issue, but I will answer anyway for the record: This is by design. The parameter TerritoryID is exposed as a picklist in the API. We have chosen to design our functions so that you have to provide the picklist _label_, in this case the territory name, not the integer id of the picklist. We think it saves a lot of time to be able to select picklist values by label, not index integer while coding.
